from typing import TypedDict, List, Dict, Any, Optional

class ResearchState(TypedDict):
    """
    Shared State Schema for the Multi-Agent Research Assistant Graph.
    Passed between Planner, Research, Writer, and Critic agents.
    """
    topic: str                             # User's primary research request
    sub_questions: List[str]               # 3-4 sub-questions generated by Planner
    search_queries: List[str]              # Dynamic search queries optimized for search engines
    retrieved_docs: List[Dict[str, Any]]   # Passages retrieved from vector store
    web_results: List[Dict[str, Any]]      # Search results from live web search
    draft_report: str                      # Current draft produced by Writer Agent
    critic_score: float                    # Groundedness score (0.0 to 1.0)
    critic_feedback: str                   # Detailed critic review & missing items
    revision_count: int                    # Self-correction loop counter
    final_report: str                      # Completed markdown report with citations
    status_log: List[str]                  # Step-by-step progress messages for UI
