"""
state.py — Shared State Schema (The Multi-Agent Memory Bus)
============================================================

📚 BEGINNER EXPLANATION — What is "State" in a Multi-Agent System?
    Imagine you're managing a research team of 4 people:
    1. A Planner who breaks down the research topic
    2. A Researcher who finds information
    3. A Writer who creates the report
    4. A Critic who reviews the report

    In real life, these team members share a WHITEBOARD where they write their progress.
    The Planner writes sub-questions on the whiteboard. The Researcher adds found articles.
    The Writer reads everything and produces a draft. The Critic scores it.

    In our code, `ResearchState` IS that whiteboard — a shared Python dictionary that
    every agent node reads from and writes to.

🏗️ DESIGN PATTERN — Data Transfer Object (DTO) / Shared Bus Pattern:
    - Agents do NOT communicate via natural language messages to each other.
    - Instead, they interact through a structured, typed dictionary.
    - Each agent reads the keys it needs, does its work, and returns ONLY
      the keys it wants to update.

    ANALOGY: It's like a relay race baton — each runner (agent) receives the baton
    (state), adds their contribution, and passes it to the next runner.

🔧 WHY TypedDict (not a regular dict)?
    - TypedDict provides STATIC TYPE CHECKING at development time.
    - Your IDE (VS Code, PyCharm) can catch typos like `state["tpoic"]` before runtime.
    - It documents the exact shape of the data contract for the entire graph.
    - LangGraph uses the TypedDict to understand which keys exist in the state.

📁 ARCHITECTURE ROLE:
    This file sits at LAYER 2 (Graph Orchestration) — it defines the memory
    contract that LAYER 3 agents operate on.

💡 KEY INSIGHT FOR LEARNERS:
    The state is MUTABLE. When `planner_agent_node` returns `{"sub_questions": [...]}`,
    LangGraph MERGES those keys into the existing state dictionary. Keys that the agent
    doesn't return remain unchanged. This is called "partial state mutation."
"""

from typing import TypedDict, List, Dict, Any, Optional


class ResearchState(TypedDict):
    """
    Shared State Schema for the Multi-Agent Research Assistant Graph.

    This TypedDict defines the COMPLETE memory contract for the system.
    Every agent node receives this state as input and returns a dictionary
    containing ONLY the keys it wants to update.

    📚 FIELD LIFECYCLE — When each field gets populated:

    ┌─────────────────────┬──────────────────────────────────┬──────────────────────────┐
    │ Field               │ Set By                           │ Read By                  │
    ├─────────────────────┼──────────────────────────────────┼──────────────────────────┤
    │ topic               │ User (via Streamlit UI)          │ Planner, Writer          │
    │ sub_questions       │ Planner Agent                    │ Writer Agent             │
    │ search_queries      │ Planner Agent (+ Critic updates) │ Research Agent           │
    │ retrieved_docs      │ Research Agent (Vector Store)     │ Writer, Critic           │
    │ web_results         │ Research Agent (Web Search)       │ Writer, Critic           │
    │ draft_report        │ Writer Agent                     │ Critic, Finalizer        │
    │ critic_score        │ Critic Agent                     │ should_continue() router │
    │ critic_feedback     │ Critic Agent                     │ Writer (on revision)     │
    │ revision_count      │ increment_revision_node          │ should_continue() router │
    │ final_report        │ Finalizer Node                   │ Streamlit UI (app.py)    │
    │ status_log          │ ALL nodes (append messages)      │ Streamlit UI (progress)  │
    └─────────────────────┴──────────────────────────────────┴──────────────────────────┘
    """

    # ──── USER INPUT ────────────────────────────────────────────
    topic: str
    """The user's primary research request/topic submitted via the Streamlit text input.
    Example: "Impact of Quantum Computing on Modern Cryptography in 2026"
    Set once at the start and never modified by any agent."""

    # ──── PLANNER AGENT OUTPUTS ─────────────────────────────────
    sub_questions: List[str]
    """3-4 targeted research sub-questions generated by the Planner Agent.
    These decompose the broad topic into specific, answerable research angles.
    Example: ["What is Shor's algorithm's impact on RSA?", "What are NIST PQC standards?"]"""

    search_queries: List[str]
    """Clean, 3-5 word search engine query strings optimized for web search APIs.
    Initially set by Planner, but CAN BE UPDATED by the Critic Agent during
    revision loops when the Critic identifies missing evidence areas.
    Example: ["quantum computing RSA impact", "NIST post quantum standards 2026"]"""

    # ──── RESEARCH AGENT OUTPUTS ────────────────────────────────
    retrieved_docs: List[Dict[str, Any]]
    """Document chunks retrieved from the local ChromaDB vector store.
    Each dict contains: {"query": str, "content": str, "source": str}
    Empty list if no documents have been uploaded to the vector store."""

    web_results: List[Dict[str, Any]]
    """Search results from live DuckDuckGo web search (fetched in parallel threads).
    Each dict contains: {"query": str, "title": str, "url": str, "snippet": str}
    These provide real-time, up-to-date evidence from the internet."""

    # ──── WRITER AGENT OUTPUTS ──────────────────────────────────
    draft_report: str
    """The current Markdown research report draft produced by the Writer Agent.
    Contains structured sections (Executive Summary, Key Takeaways, Analysis,
    Comparison Table, Conclusion) with inline numerical citations [1], [2], etc.
    Updated on each revision cycle when the Writer incorporates Critic feedback."""

    # ──── CRITIC AGENT OUTPUTS ──────────────────────────────────
    critic_score: float
    """Groundedness quality score from 0.0 to 1.0 assigned by the Critic Agent.
    - >= 0.8: Report passes quality gate → routes to Finalizer
    - < 0.8:  Report needs revision → routes back to Research node
    This score drives the conditional routing logic in should_continue()."""

    critic_feedback: str
    """Detailed textual review from the Critic Agent explaining what's missing,
    what claims lack citations, and what topics need deeper coverage.
    Fed back to the Writer Agent on revision loops to guide improvements."""

    # ──── GRAPH CONTROL FLOW ────────────────────────────────────
    revision_count: int
    """Counter tracking how many reflection/revision loops have occurred.
    Incremented by increment_revision_node each time the Critic rejects a draft.
    When revision_count >= MAX_REVISIONS (default 2), the graph force-finalizes
    regardless of the critic_score to prevent infinite loops."""

    # ──── FINAL OUTPUT ──────────────────────────────────────────
    final_report: str
    """The completed, finalized Markdown research report ready for display and download.
    Set by the Finalizer Node. Identical to draft_report if quality passed,
    or includes a quality warning note if force-finalized after max revisions."""

    # ──── UI OBSERVABILITY ──────────────────────────────────────
    status_log: List[str]
    """Step-by-step progress messages appended by every node for real-time UI display.
    Example entries:
    - "🎯 Planner Agent: Analyzing topic..."
    - "🌐 Research Agent: Searching live web..."
    - "✍️ Writer Agent: Synthesizing report..."
    - "🧐 Critic Agent: Fact-checking..."
    - "✅ Finalizer: Research completed!"
    Displayed in the Streamlit st.status() container during execution."""
