"""
graph.py — LangGraph StateGraph Assembly & Conditional Routing
================================================================

📚 BEGINNER EXPLANATION — What is a State Graph?
    A State Graph is a way to organize a program as a series of "nodes" (steps)
    connected by "edges" (transitions). Think of it like a flowchart:
    
    [Planner] → [Research] → [Writer] → [Critic] → Decision?
                                                      ↙    ↘
                                               [Revise]   [Finalize]
                                                  ↓
                                             [Research] (loop back)

    Unlike a simple linear pipeline (A → B → C → Done), a State Graph can have
    LOOPS and CONDITIONAL BRANCHES. The Critic's score determines whether we
    loop back for revision or proceed to finalization.

🏗️ KEY CONCEPTS FOR BEGINNERS:
    1. NODE = A Python function that processes state and returns updates
    2. EDGE = A connection from one node to the next
    3. LINEAR EDGE = Always goes from A → B (unconditional)
    4. CONDITIONAL EDGE = Goes to A or B based on a function's return value
    5. ENTRY POINT = Which node runs first (our Planner)
    6. END = Special marker that terminates the graph execution

🏗️ DESIGN PATTERN — State Machine Pattern:
    A State Machine has:
    - STATES (our ResearchState dictionary)
    - TRANSITIONS (edges between nodes)
    - GUARDS (conditional edges that check state values)
    
    LangGraph implements this pattern with a clean API:
    - builder.add_node() → register a processing step
    - builder.add_edge() → add an unconditional transition
    - builder.add_conditional_edges() → add a guarded transition
    - builder.compile() → freeze the graph and make it executable

📊 COMPLETE EXECUTION FLOW:
    
    First Pass:
    planner → research → writer → critic → should_continue()
                                                ↓
                                    Score >= 0.8? → finalizer → END
                                    Score < 0.8?  → increment_revision → research (loop)
    
    Revision Pass (if triggered):
    research → writer → critic → should_continue()
                                      ↓
                          Score >= 0.8 OR revisions >= MAX? → finalizer → END
                          Score < 0.8 AND revisions < MAX?  → increment_revision → research

📁 ARCHITECTURE ROLE:
    LAYER 2 (Graph Orchestration) — The conductor of the entire system.
    This file imports all agent nodes and tool functions, wires them
    into a LangGraph StateGraph, and exports the compiled graph.
"""

import logging
from typing import Dict, Any, Literal
from langgraph.graph import StateGraph, END
from src.state import ResearchState
from src.agents.planner import planner_agent_node
from src.agents.writer import writer_agent_node
from src.agents.critic import critic_agent_node
from src.tools.web_search import search_web
from src.tools.vector_store import LocalVectorStore
from config import MAX_REVISIONS

# Setup module-level logger
logger = logging.getLogger(__name__)


# ══════════════════════════════════════════════════════════════
# HELPER NODES
# These are lightweight processing nodes that don't call LLMs.
# They handle data retrieval and graph control flow operations.
# ══════════════════════════════════════════════════════════════

def research_agent_node(state: dict) -> dict:
    """
    Research Node — Executes parallel web search and local vector retrieval.

    📚 HOW IT WORKS:
        This node is the "data gathering" step. It takes the search queries
        generated by the Planner (or refined by the Critic) and:
        1. Runs live web searches via DuckDuckGo (parallel threads)
        2. Queries the local ChromaDB vector store for uploaded documents
        3. Returns both result sets to be used by the Writer

    📚 WHY TWO DATA SOURCES?
        - Web Search: Provides real-time, up-to-date information from the internet
        - Vector Store: Provides context from user-uploaded PDFs/documents
        Together, they give the Writer both current web knowledge AND domain-specific
        private knowledge — this is the hybrid retrieval strategy.

    📚 BEGINNER NOTE — This is NOT an LLM node:
        Unlike the Planner, Writer, and Critic, the Research node doesn't call
        an LLM. It calls external tools (search APIs, database queries).
        This is a common pattern in agent systems: not every node needs AI.

    Args:
        state: Shared state containing search_queries from the Planner/Critic.

    Returns:
        dict: Updated state with web_results and retrieved_docs.
    """
    search_queries = state.get("search_queries", [])
    status_log = state.get("status_log", [])

    status_log.append(f"🌐 Research Agent: Searching live web & local vector store for queries: {search_queries}...")
    logger.info(f"Research node executing {len(search_queries)} search queries.")

    # ──────────────────────────────────────────────────────────
    # 1. Live Web Search (DuckDuckGo via ThreadPoolExecutor)
    # Executes all queries in PARALLEL threads for speed.
    # See src/tools/web_search.py for the concurrency implementation.
    # ──────────────────────────────────────────────────────────
    web_results = search_web(search_queries)

    # ──────────────────────────────────────────────────────────
    # 2. Local ChromaDB Vector Search
    # Queries the persistent vector store for relevant document chunks.
    # Returns empty list if no documents have been uploaded.
    # ──────────────────────────────────────────────────────────
    vector_store = LocalVectorStore()
    retrieved_docs = vector_store.search(search_queries)

    logger.info(f"Research complete: {len(web_results)} web results, {len(retrieved_docs)} vector docs.")

    return {
        "web_results": web_results,
        "retrieved_docs": retrieved_docs,
        "status_log": status_log
    }


def increment_revision_node(state: dict) -> dict:
    """
    Helper Node — Increments the revision counter on reflection loop.

    📚 WHY IS THIS A SEPARATE NODE?
        In LangGraph, conditional edges route between NODES, not arbitrary code.
        We need a dedicated node to increment `revision_count` because:
        1. The Critic node handles evaluation (it shouldn't also handle counting)
        2. This keeps each node's responsibility SINGLE and CLEAR
        3. It gives us a clean spot to log the revision event

    📚 DESIGN PRINCIPLE — Single Responsibility:
        Each node does exactly ONE thing. The increment node only increments.
        This makes the system easier to debug and test.

    Args:
        state: Shared state containing current revision_count.

    Returns:
        dict: Updated revision_count (+1) and status_log.
    """
    current_revisions = state.get("revision_count", 0)
    status_log = state.get("status_log", [])
    status_log.append(f"🔄 Reflection Loop: Revision #{current_revisions + 1} initiated based on Critic Feedback...")
    logger.info(f"Revision loop triggered: revision #{current_revisions + 1}")
    return {
        "revision_count": current_revisions + 1,
        "status_log": status_log
    }


def finalizer_node(state: dict) -> dict:
    """
    Finalizer Node — Packages the final report for UI display.

    📚 WHAT THE FINALIZER DOES:
        1. Takes the latest draft_report (which has passed the Critic OR exhausted
           max revisions)
        2. If the report was force-finalized (score < 0.8 after max revisions),
           appends a quality warning note so the user knows
        3. Sets the final_report key which the Streamlit UI reads

    📚 WHY A SEPARATE FINALIZER?
        - It separates "report quality evaluation" (Critic) from "report packaging" (Finalizer)
        - It gives us a single, predictable exit point in the graph
        - It's where you'd add post-processing like formatting, watermarking, or metadata

    Args:
        state: Shared state containing draft_report and critic_score.

    Returns:
        dict: Updated final_report and status_log.
    """
    draft_report = state.get("draft_report", "")
    critic_score = state.get("critic_score", 1.0)
    status_log = state.get("status_log", [])

    status_log.append("✅ Finalizer Node: Research completed successfully!")

    final_report = draft_report

    # Append quality warning if the report was force-finalized below threshold
    if critic_score < 0.8:
        final_report += (
            f"\n\n---\n> ⚠️ **Quality Note:** Final report generated after maximum "
            f"reflection iterations. Critic Quality Score: `{critic_score:.2f}/1.00`."
        )
        logger.warning(f"Report force-finalized with below-threshold score: {critic_score:.2f}")

    return {
        "final_report": final_report,
        "status_log": status_log
    }


# ══════════════════════════════════════════════════════════════
# CONDITIONAL ROUTING FUNCTION
# This is the "brain" of the graph's control flow.
# ══════════════════════════════════════════════════════════════

def should_continue(state: dict) -> Literal["continue_revision", "finalize"]:
    """
    Conditional Routing Edge — The decision gate after the Critic node.

    📚 THE ROUTING LOGIC:
        This function is called by LangGraph after the Critic node finishes.
        It checks TWO conditions:
        
        1. Quality Check: Is critic_score >= 0.8? (report is good enough)
        2. Safety Check: Is revision_count >= MAX_REVISIONS? (prevent infinite loops)
        
        If EITHER condition is true → "finalize" (proceed to Finalizer)
        If NEITHER is true → "continue_revision" (loop back for another attempt)

    📚 WHY TWO CONDITIONS (not just score)?
        Without the revision_count check, a harsh Critic could score every draft
        below 0.8, causing the system to loop FOREVER. The MAX_REVISIONS cap
        (default: 2) guarantees the graph ALWAYS terminates.
        
        This is called "loop termination guarantee" — a critical property
        for any system with cycles. In computer science, this is related to
        the Halting Problem.

    📚 BEGINNER NOTE — What is Literal["continue_revision", "finalize"]?
        This type hint tells Python (and your IDE) that this function can ONLY
        return one of these two specific strings. LangGraph uses these strings
        to look up which node to route to next (see add_conditional_edges below).

    Args:
        state: Shared state containing critic_score and revision_count.

    Returns:
        "finalize" if the report passes quality OR max revisions reached.
        "continue_revision" if the report needs more work and budget remains.
    """
    score = state.get("critic_score", 0.0)
    revisions = state.get("revision_count", 0)

    if score >= 0.8 or revisions >= MAX_REVISIONS:
        logger.info(f"Routing to FINALIZE (score={score:.2f}, revisions={revisions}/{MAX_REVISIONS})")
        return "finalize"
    else:
        logger.info(f"Routing to REVISION (score={score:.2f}, revisions={revisions}/{MAX_REVISIONS})")
        return "continue_revision"


# ══════════════════════════════════════════════════════════════
# GRAPH ASSEMBLY FUNCTION
# This is where all nodes and edges are wired together.
# ══════════════════════════════════════════════════════════════

def create_research_graph() -> StateGraph:
    """
    Builds and compiles the Multi-Agent Research Assistant StateGraph.

    📚 STEP-BY-STEP ASSEMBLY:
        This function follows a 4-step pattern common to all LangGraph applications:
        
        Step 1: Create a StateGraph builder with the state schema
        Step 2: Add all nodes (processing functions)
        Step 3: Wire edges (transitions between nodes)
        Step 4: Compile the graph into an executable object

    📚 BEGINNER ANALOGY:
        Think of this like building a railway system:
        - add_node() = building train stations
        - set_entry_point() = marking the starting station
        - add_edge() = laying tracks between stations
        - add_conditional_edges() = building track switches that change based on signals
        - compile() = opening the railway for operation

    Returns:
        StateGraph: A compiled, executable graph ready for .invoke(initial_state).
    """
    # ──────────────────────────────────────────────────────────
    # STEP 1: Create the StateGraph builder
    #
    # ResearchState is passed as the schema — LangGraph uses this to
    # understand the shape of the shared state dictionary.
    # ──────────────────────────────────────────────────────────
    builder = StateGraph(ResearchState)

    # ──────────────────────────────────────────────────────────
    # STEP 2: Register all nodes (processing stations)
    #
    # Each add_node() call associates a string name with a function.
    # The string name is used in edges to reference this node.
    # ──────────────────────────────────────────────────────────
    builder.add_node("planner", planner_agent_node)         # Node 1: Task decomposition
    builder.add_node("research", research_agent_node)       # Node 2: Data gathering
    builder.add_node("writer", writer_agent_node)           # Node 3: Report synthesis
    builder.add_node("critic", critic_agent_node)           # Node 4: Quality evaluation
    builder.add_node("increment_revision", increment_revision_node)  # Helper: revision counter
    builder.add_node("finalizer", finalizer_node)           # Node 5: Final packaging

    # ──────────────────────────────────────────────────────────
    # STEP 3A: Define the LINEAR FLOW (unconditional edges)
    #
    # These edges form the main pipeline:
    # planner → research → writer → critic
    #
    # Each add_edge(A, B) means: "After A finishes, ALWAYS run B next."
    # ──────────────────────────────────────────────────────────
    builder.set_entry_point("planner")              # Start here when graph.invoke() is called
    builder.add_edge("planner", "research")         # After planning, gather evidence
    builder.add_edge("research", "writer")          # After research, write the report
    builder.add_edge("writer", "critic")            # After writing, evaluate quality

    # ──────────────────────────────────────────────────────────
    # STEP 3B: Define the CONDITIONAL ROUTING (the reflection loop)
    #
    # After the Critic node, call should_continue() to decide:
    #   "continue_revision" → go to increment_revision node
    #   "finalize"          → go to finalizer node
    #
    # The second argument is the routing function.
    # The third argument maps return values to node names.
    # ──────────────────────────────────────────────────────────
    builder.add_conditional_edges(
        "critic",                       # Source node: after Critic finishes...
        should_continue,                # Call this function to decide where to go
        {
            "continue_revision": "increment_revision",  # If function returns this → go here
            "finalize": "finalizer"                      # If function returns this → go here
        }
    )

    # ──────────────────────────────────────────────────────────
    # STEP 3C: Complete the revision loop and termination
    #
    # increment_revision → research: Loop back to gather new evidence
    # finalizer → END: Terminate the graph execution
    #
    # END is a special LangGraph constant that signals "stop executing."
    # ──────────────────────────────────────────────────────────
    builder.add_edge("increment_revision", "research")  # Loop back to research
    builder.add_edge("finalizer", END)                   # Graph terminates here

    # ──────────────────────────────────────────────────────────
    # STEP 4: Compile the graph
    #
    # compile() freezes the graph structure and returns an executable
    # object. After compilation, you can call graph.invoke(state).
    #
    # 📚 WHAT compile() DOES INTERNALLY:
    # - Validates that all edges reference existing nodes
    # - Checks for unreachable nodes (dead code detection)
    # - Builds the execution scheduler
    # - Returns a CompiledGraph that supports .invoke() and .stream()
    # ──────────────────────────────────────────────────────────
    logger.info("Research graph compiled successfully with conditional reflection loop.")
    return builder.compile()
